id: P010716
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:21:15.808323
source_metadata:
  id: bdr:W1CZ2511
  title: དགེ་ལྡན་ལེགས་བཤད་གླིང་གི་གཙུག་ལག་ཁང་གི་དཀར་ཆག་མདོར་བསྡུས་ཤེལ་དཀར་མེ་ལོང་
  author: ''
  volumes:
    754fd0f1d3484e38a9d57e6dd0b951b4:
      image_group_id: I1CZ2524
      title: ''
      volume_number: 1
      total_pages: 67
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
