id: I044E7F83
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T14:59:01+00:00'
last_modified: '2022-06-08T17:00:54.131664+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2511
  title: དགེ་ལྡན་ལེགས་བཤད་གླིང་གི་གཙུག་ལག་ཁང་གི་དཀར་ཆག་མདོར་བསྡུས་ཤེལ་དཀར་མེ་ལོང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    956B:
      image_group_id: I1CZ2524
      title: ''
      total_pages: 67
      order: 1
      base_file: 956B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
